server:
  port: 8900

spring:
  application:
    name: feign-provider

eureka:
  client:
    register-with-eureka: false #服务消费者可以不向服务注册中心注册服务
    service-url:
      defaultZone: http://192.168.1.106:8300/eureka/
    fetch-registry: true  #服务消费者客户端需要去检索服务