server:
  port: 9001
spring:
  application:
    name: nacos-provider

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        # 指定集群名称
        # cluster-name: nj
        # metadata:
          # version: v3
        #ephemeral: false
        namespace: gatsby
